runtime: go111

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 50

handlers:
- url: /
  secure: always
  static_files: dist/storiesboard/index.html
  upload: dist/storiesboard/.*
- url: /(.*\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  upload: dist/storiesboard/.*\.js
- url: /(.*\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  mime_type: text/css
  upload: dist/storiesboard/.*\.css
- url: /(.*\.svg)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  upload: dist/storiesboard/.*\.svg
- url: /(.*\.png)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  upload: dist/storiesboard/.*\.png
- url: /(.*\.jpg)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  upload: dist/storiesboard/.*\.jpg
- url: /(.*\.jpeg)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/storiesboard/\1
  upload: dist/storiesboard/.*\.jpeg  
- url: /favicon.ico
  secure: always
  static_files: dist/storiesboard/favicon.ico
  upload: dist/storiesboard/.*
- url: /.*
  secure: always
  static_files: dist/storiesboard/index.html
  upload: dist/storiesboard/.*
